In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
base_credit = pd.read_csv('database/credit_data_save.csv')
base_credit.shape

(2000, 5)

## Separando as colunas Previsores e a Classe

In [3]:
X_credit = base_credit.iloc[:,1:4].values
X_credit

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [4]:
y_credit = base_credit.iloc[:,4].values
y_credit

array([0, 0, 0, ..., 1, 0, 0])

## Divisão entre previsores e classe Escalonamento dos atributos

In [5]:
X_credit[:,0].min(),X_credit[:,1].min(),X_credit[:,2].min()

(20014.4894700497, 18.055188510566897, 1.37762959325451)

In [6]:
X_credit[:,0].max(),X_credit[:,1].max(),X_credit[:,2].max()

(69995.6855783239, 63.971795841120205, 13766.0512393337)

## Escalonamento dos atributos

In [7]:
X_credit[:,0].min()

20014.4894700497

In [8]:
X_credit[:,0].max()

69995.6855783239

 <h2>Para realizar a escala entre diversos valore que impençam uma super valorização de determindo atributo
 podemos usar tando a padronização quanto a Normalização, para este estudo usaremos a Padronização</h2>

<img src='img/escalonamento.png'>

In [9]:
scaler_credit = StandardScaler()
X_credit = scaler_credit.fit_transform(X_credit)
X_credit[:,0].min(),X_credit[:,1].min(),X_credit[:,2].min()

(-1.7676158019964077, -1.7264154144794286, -1.4592791099462408)

In [10]:
X_credit[:,0].max(),X_credit[:,1].max(),X_credit[:,2].max()

(1.7220222385319197, 1.739366520151568, 3.0616609141708273)

In [11]:
X_credit

array([[ 1.45393393,  1.36538005,  1.20281942],
       [-0.76217555,  0.54265932,  0.69642695],
       [ 0.83682073,  1.67417101,  1.17471147],
       ...,
       [-0.07122592, -0.97448606,  0.35420081],
       [-0.11000289,  1.73936652, -0.92675625],
       [ 1.682986  ,  1.14917551,  0.96381038]])

In [16]:
Xtreinamento, Xteste, ytreinamento, yteste = train_test_split(X_credit,y_credit,test_size=0.25, random_state=0)

In [22]:
Xtreinamento.shape,Xteste.shape,ytreinamento.shape,yteste.shape

((1500, 3), (500, 3), (1500,), (500,))